[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"  # simple async HTTP server framework
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
core = { path = "../core" }
cli = { path = "../cli" }
